name: Assign PR author
description: Assign author to the pull request

inputs:
  token:
    description: GitHub token to use for the API call
    required: true

runs:
  using: composite
  steps:
    - name: Set inputs
      env:
        INPUT_TOKEN: ${{ inputs.token }}
      run: |
        {
          echo "INPUT_TOKEN=$INPUT_TOKEN"
        } >> $GITHUB_ENV
      shell: bash

    - name: Assign author
      if: github.event.action == 'opened' && github.event.pull_request.user.type == 'User'
      uses: octokit/graphql-action@v3.0.2
      with:
        token: ${{ env.INPUT_TOKEN }}
        query: |
          mutation AddAssigneesToAssignable($id: ID!, $assignee: ID!) {
            addAssigneesToAssignable(input: { assignableId: $id, assigneeIds: [$assignee] }) {
              clientMutationId
            }
          }
        id: ${{ github.event.pull_request.node_id }}
        assignee: ${{ github.event.pull_request.user.node_id }}
