engineStrict: true
gitChecks: false
includeWorkspaceRoot: true
minimumReleaseAge: 4320 # 3 days

minimumReleaseAgeExclude:
  - '@cluerise/*'

publicHoistPattern:
  - '@commitlint/cli'
  - eslint
  - lint-staged
  - prettier
  - prettier-plugin-sh
