gitChecks: false
minimumReleaseAge: 4320 # 3 days
optimisticRepeatInstall: false

allowBuilds:
  unrs-resolver: false

minimumReleaseAgeExclude:
  - '@cluerise/*'

publicHoistPattern:
  - '@commitlint/cli'
  - eslint
  - lint-staged
  - prettier
  - prettier-plugin-sh
