name: Auto-merge PR
description: Enable auto-merge for bot's PR

inputs:
  token:
    description: GitHub token to use for the API call
    required: true
  title:
    description: Custom pull request title
  trusted-bot:
    description: Enable auto merge for all pull requests from the trusted bot

runs:
  using: composite
  steps:
    - name: Set inputs
      env:
        token: ${{ inputs.token }}
        title: ${{ inputs.title || github.event.pull_request.title }}
        trusted-bot: ${{ inputs.trusted-bot }}
      run: |
        echo "INPUT_TOKEN=${{ env.token }}" >> $GITHUB_ENV;
        echo "INPUT_TITLE=${{ env.title }}" >> $GITHUB_ENV;
        echo "INPUT_TRUSTED_BOT=${{ env.trusted-bot }}" >> $GITHUB_ENV;
      shell: bash

    - name: Auto-merge
      if: >-
        (
          github.event.action == 'opened' ||
          github.event.action == 'synchronize' ||
          github.event.action == 'reopened'
        ) &&
        (
          github.event.pull_request.user.login == 'dependabot[bot]' ||
          github.event.pull_request.user.login == 'github-actions[bot]' ||
          github.event.pull_request.user.login == env.INPUT_TRUSTED_BOT
        )
      uses: octokit/graphql-action@v2.3.2
      with:
        token: ${{ env.INPUT_TOKEN }}
        query: |
          mutation enablePullRequestAutoMerge($id: ID!, $message: String!) {
            enablePullRequestAutoMerge(input: {pullRequestId: $id, commitHeadline: $message, commitBody: "", mergeMethod: SQUASH}) {
              clientMutationId
            }
          }
        id: ${{ github.event.pull_request.node_id }}
        message: '"${{ env.INPUT_TITLE }} (#${{ github.event.pull_request.number }})"'
