name: Review PR
description: Approve a pull request or request a review

inputs:
  token:
    description: GitHub token to use for the API call
    required: true
  trusted-user:
    description: Approve all pull requests from the trusted user
    required: true
  trusted-bot:
    description: Approve all pull requests from the trusted bot except for releases
    required: true
  reviewer:
    description: A user for requesting reviews
    required: true
  dependency-approved:
    description: A boolean whether the updated dependency should be approved
    required: true

runs:
  using: composite
  steps:
    - name: Set inputs
      env:
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_TRUSTED_USER: ${{ inputs.trusted-user }}
        INPUT_TRUSTED_BOT: ${{ inputs.trusted-bot }}
        INPUT_REVIEWER: ${{ inputs.reviewer }}
        INPUT_DEPENDENCY_APPROVED: ${{ inputs.dependency-approved }}
      run: |
        {
          echo "INPUT_TOKEN=$INPUT_TOKEN"
          echo "INPUT_TRUSTED_USER=$INPUT_TRUSTED_USER"
          echo "INPUT_TRUSTED_BOT=$INPUT_TRUSTED_BOT"
          echo "INPUT_REVIEWER=$INPUT_REVIEWER"
          echo "INPUT_DEPENDENCY_APPROVED=$INPUT_DEPENDENCY_APPROVED"
        } >> $GITHUB_ENV
      shell: bash

    - name: Approve
      if: >-
        (
          github.event.action == 'opened' ||
          github.event.action == 'synchronize' ||
          github.event.action == 'reopened'
        ) &&
        (
          github.event.pull_request.user.login == env.INPUT_TRUSTED_USER ||
          (
            github.event.pull_request.user.login == env.INPUT_TRUSTED_BOT &&
            (!startsWith(github.head_ref, 'deps-') || env.INPUT_DEPENDENCY_APPROVED == 'true') &&
            github.head_ref != 'release'
          ) ||
          (
            github.event.pull_request.user.login == 'dependabot[bot]' &&
            env.INPUT_DEPENDENCY_APPROVED == 'true'
          )
        )
      uses: octokit/graphql-action@v3.0.2
      with:
        token: ${{ env.INPUT_TOKEN }}
        query: |
          mutation ApprovePullRequest($id: ID!) {
            addPullRequestReview(input: { pullRequestId: $id, event: APPROVE }) {
              clientMutationId
            }
          }
        id: ${{ github.event.pull_request.node_id }}

    - name: Get user for review
      id: get-user-id
      uses: octokit/graphql-action@v3.0.2
      with:
        token: ${{ env.INPUT_TOKEN }}
        query: |
          query GetUserId($login: String!) {
            user(login: $login) {
              id
            }
          }
        login: ${{ env.INPUT_REVIEWER }}

    - name: Request review
      if: >-
        (
          github.event.action == 'opened' ||
          github.event.action == 'synchronize' ||
          github.event.action == 'reopened'
        ) &&
        (
          (
            github.event.pull_request.user.login == env.INPUT_TRUSTED_BOT &&
            (
              (startsWith(github.head_ref, 'deps-') && env.INPUT_DEPENDENCY_APPROVED == 'false') ||
              github.head_ref == 'release'
            )
          ) ||
          (
            github.event.pull_request.user.login == 'dependabot[bot]' &&
            env.INPUT_DEPENDENCY_APPROVED == 'false'
          )
        )
      uses: octokit/graphql-action@v3.0.2
      with:
        token: ${{ env.INPUT_TOKEN }}
        query: |
          mutation RequestReview($id: ID!, $user: ID!) {
            requestReviews(input: { pullRequestId: $id, userIds: [$user] }) {
              clientMutationId
            }
          }
        id: ${{ github.event.pull_request.node_id }}
        user: ${{ fromJSON(steps.get-user-id.outputs.data).user.id }}
