name: Get GH app token
description: Get GitHub app token

inputs:
  app-id:
    type: string
    description: GitHub app ID
    required: true
  private-key:
    type: string
    description: GitHub app private key
    required: true

outputs:
  token:
    description: GitHub app installation access token
    value: ${{ steps.get-token.outputs.token }}

runs:
  using: composite
  steps:
    - name: Install Octokit
      run: npm install octokit
      shell: bash

    - name: Get token
      id: get-token
      uses: actions/github-script@v7.0.1
      with:
        script: |
          import { App, Octokit } from 'octokit';

          const app = new App({
            appId: core.getInput('app-id', { required: true }),
            privateKey: core.getInput('private-key', { required: true }),
            Octokit: Octokit.defaults({
              request: {
                fetch
              }
            })
          });

          const installation = await app.octokit.rest.apps.getRepoInstallation({
            owner: context.repo.owner,
            repo: context.repo.repo
          });

          const installationAccessToken = await app.octokit.rest.apps.createInstallationAccessToken({
            installation_id: installation.data.id
          });

          const accessToken = installationAccessToken.data.token;

          core.setSecret(accessToken);
          core.setOutput('token', accessToken);
        app-id: ${{ inputs.app-id }}
        private-key: ${{ inputs.private-key }}
