name: Install
description: Checkout and install dependencies

inputs:
  ref:
    description: >
      The branch, tag or SHA to checkout. When checking out the repository that
      triggered a workflow, this defaults to the reference or SHA for that
      event. Otherwise, uses the default branch.
  fetch-depth:
    description: 'Number of commits to fetch. 0 indicates all history for all branches and tags. Default: 1'
  manager:
    description: Package manager (pnpm, npm, or yarn)
  node-version:
    description: 'Node.js version to use. Examples: 12.x, 10.15.1, >=10.15.0'
  node-version-file:
    description: File containing the Node.js version to use
  registry-url:
    description: NPM package registry URL

runs:
  using: composite
  steps:
    - name: Set inputs
      env:
        ref: ${{ inputs.ref }}
        fetch-depth: ${{ inputs.fetch-depth }}
        manager: ${{ inputs.manager || 'pnpm' }}
        node-version: ${{ inputs.node-version }}
        node-version-file: ${{ inputs.node-version-file || '.nvmrc' }}
        registry-url: ${{ inputs.registry-url }}
      run: |
        {
          echo "INPUT_REF=${{ env.ref }}"
          echo "INPUT_FETCH_DEPTH=${{ env.fetch-depth }}"
          echo "INPUT_MANAGER=${{ env.manager }}"
          echo "INPUT_NODE_VERSION=${{ env.node-version }}"
          echo "INPUT_NODE_VERSION_FILE=${{ env.node-version-file }}"
          echo "INPUT_REGISTRY_URL=${{ env.registry-url }}"
        } >> $GITHUB_ENV
      shell: bash

    - name: Checkout
      uses: actions/checkout@v4.2.2
      with:
        ref: ${{ env.INPUT_REF }}
        fetch-depth: ${{ env.INPUT_FETCH_DEPTH }}

    - name: Setup PNPM
      if: env.INPUT_MANAGER == 'pnpm'
      uses: pnpm/action-setup@v4.1.0
      with:
        run_install: false

    - name: Setup Node.js
      uses: actions/setup-node@v4.4.0
      with:
        cache: ${{ env.INPUT_MANAGER }}
        node-version: ${{ env.INPUT_NODE_VERSION }}
        node-version-file: ${{ env.INPUT_NODE_VERSION_FILE }}
        registry-url: ${{ env.INPUT_REGISTRY_URL }}

    - name: Install PNPM dependencies
      if: env.INPUT_MANAGER == 'pnpm'
      run: pnpm install
      shell: bash

    - name: Install NPM dependencies
      if: env.INPUT_MANAGER == 'npm'
      run: npm ci
      shell: bash

    - name: Install Yarn dependencies
      if: env.INPUT_MANAGER == 'yarn'
      run: yarn
      shell: bash
