name: Install
description: Checkout and install dependencies

inputs:
  ref:
    description: >
      The branch, tag or SHA to checkout. When checking out the repository that
      triggered a workflow, this defaults to the reference or SHA for that
      event. Otherwise, uses the default branch.
  fetch-depth:
    description: 'Number of commits to fetch. 0 indicates all history for all branches and tags. Default: 1'
  manager:
    description: Package manager (npm or yarn)
    default: npm
  node-version:
    description: 'Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0'
  node-version-file:
    description: 'File containing the version Spec of the version to use. Default: .nvmrc'
    default: .nvmrc
  registry-url:
    description: NPM package registry URL

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2
      with:
        ref: ${{ inputs.ref }}
        fetch-depth: ${{ inputs.fetch-depth }}

    - name: Check lock file version
      if: inputs.manager == 'npm'
      run: >-
        grep '"lockfileVersion": 3' package-lock.json
      shell: bash

    - name: Setup Node.js
      uses: actions/setup-node@v4.2.0
      with:
        cache: ${{ inputs.manager }}
        node-version: ${{ inputs.node-version }}
        node-version-file: ${{ inputs.node-version-file }}
        registry-url: ${{ inputs.registry-url }}

    - name: Install NPM dependencies
      if: inputs.manager == 'npm'
      run: npm ci
      shell: bash

    - name: Install Yarn dependencies
      if: inputs.manager == 'yarn'
      run: yarn
      shell: bash
