name: Add PR labels
description: Add labels to pull request

inputs:
  token:
    type: string
    description: GitHub token to use for the API call
    required: true
  types:
    type: string
    description: Valid commit types (JSON array)
    default: '["chore", "deps", "docs", "feat", "fix", "perf", "refactor", "release", "revert", "style", "test"]'
  scopes:
    type: string
    description: Valid commit scopes (JSON array)
    default: '["actions", "dev", "lock", "prod", "security"]'

runs:
  using: composite
  steps:
    - name: Add labels
      if: github.event.action == 'opened' || github.event.action == 'edited'
      uses: actions/github-script@v5.1.0
      with:
        github-token: ${{ inputs.token }}
        script: |
          const types = JSON.parse(core.getInput('types', { required: true }));
          const scopes = JSON.parse(core.getInput('scopes', { required: true }));

          const {title} = context.payload.pull_request;

          const type = types.find(type => title.startsWith(`${type}:`) || title.startsWith(`${type}!:`) || title.startsWith(`${type}(`));
          const scope = scopes.find(scope => title.includes(`(${scope}):`) || title.includes(`(${scope})!:`));

          const typeLabel = type ? `type: ${type}` : null;
          const scopeLabel = scope ? `scope: ${scope}` : null;

          const labels = [typeLabel, scopeLabel].filter(Boolean);

          if (labels.length > 0) {
            github.rest.issues.addLabels({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels
            });
          }
        types: ${{ inputs.types }}
        scopes: ${{ inputs.scopes }}
