name: Automate PR

on:
  pull_request_target:
    types: [opened, edited, synchronize, reopened]

jobs:
  automate-pr:
    name: Automate PR
    runs-on: ubuntu-latest

    steps:
      - name: Get bot token
        id: get-bot-token
        uses: cluerise/actions/get-github-app-token@main
        with:
          app-id: ${{ vars.CLUERISE_PUBLIC_BOT_APP_ID }}
          app-private-key: ${{ secrets.CLUERISE_PUBLIC_BOT_APP_PRIVATE_KEY }}

      - name: Assign author
        uses: cluerise/actions/assign-pr-author@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add labels
        uses: cluerise/actions/add-pr-labels@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Approve or request review
        uses: cluerise/actions/review-pr@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          trusted-user: branoholy
          trusted-bot: cluerise-public-bot[bot]
          reviewer: branoholy
          dependency-approved: >-
            ${{
              (
                startsWith(github.head_ref, 'dependabot-npm_and_yarn-cluerise-tools-') ||
                startsWith(github.head_ref, 'dependabot-npm_and_yarn-typescript-') ||
                startsWith(github.head_ref, 'dependabot-github_actions-octokit-graphql-action-') ||
                startsWith(github.head_ref, 'dependabot-github_actions-assign-pr-author-octokit-graphql-action-') ||
                startsWith(github.head_ref, 'dependabot-github_actions-auto-merge-pr-octokit-graphql-action-') ||
                startsWith(github.head_ref, 'dependabot-github_actions-check-ci-suitability-octokit-graphql-action-') ||
                startsWith(github.head_ref, 'dependabot-github_actions-review-pr-octokit-graphql-action-') ||
                startsWith(github.head_ref, 'dependabot-github_actions-actions-checkout-') ||
                startsWith(github.head_ref, 'dependabot-github_actions-install-actions-checkout-') ||
                startsWith(github.head_ref, 'dependabot-github_actions-actions-setup-node-') ||
                startsWith(github.head_ref, 'dependabot-github_actions-install-actions-setup-node-')
              )
            }}

      - name: Update title
        id: update-title
        uses: cluerise/actions/update-pr-title@main
        with:
          token: ${{ steps.get-bot-token.outputs.token }}

      - name: Auto-merge
        uses: cluerise/actions/auto-merge-pr@main
        with:
          token: ${{ steps.get-bot-token.outputs.token }}
          title: ${{ steps.update-title.outputs.title }}
          trusted-bot: cluerise-public-bot[bot]
