name: CI status

on:
  workflow_run:
    workflows: [CI]
    types: [completed]
    branches: main
  workflow_call:
    inputs:
      __external-call:
        type: boolean
        description: Do not use this input, it is an internal value to identify the workflow_call event
        default: true
    secrets:
      token:
        description: GitHub access token
        required: false
      app-id:
        description: GitHub app ID
        required: false
      private-key:
        description: GitHub app private key
        required: false

jobs:
  send-status:
    name: Send CI status
    runs-on: ubuntu-latest
    concurrency:
      group: ci-status-${{ github.event.workflow_run.head_sha }}
      cancel-in-progress: true
    env:
      CI_STATE: pending
      CI_DESCRIPTION: Waiting
      INPUT_EXTERNAL_CALL: ${{ inputs.__external-call || false }}
      SECRET_TOKEN: ${{ secrets.token }}
      SECRET_APP_ID: ${{ secrets.app-id || vars.CLUERISE_PUBLIC_BOT_APP_ID }}
      SECRET_PRIVATE_KEY: ${{ secrets.private-key || secrets.CLUERISE_PUBLIC_BOT_PRIVATE_KEY }}

    steps:
      - name: Check required secrets
        if: env.SECRET_TOKEN == null && (env.SECRET_APP_ID == null || env.SECRET_PRIVATE_KEY == null)
        run: exit 1
        shell: bash

      - name: Get bot token (main)
        id: get-bot-token-main
        if: env.INPUT_EXTERNAL_CALL == 'false' && env.SECRET_TOKEN == null
        uses: cluerise/actions/get-github-app-token@main
        with:
          app-id: ${{ env.SECRET_APP_ID }}
          private-key: ${{ env.SECRET_PRIVATE_KEY }}

      - name: Get bot token (version)
        id: get-bot-token-version
        if: env.INPUT_EXTERNAL_CALL == 'true' && env.SECRET_TOKEN == null
        uses: cluerise/actions/get-github-app-token@v2.2.1
        with:
          app-id: ${{ env.SECRET_APP_ID }}
          private-key: ${{ env.SECRET_PRIVATE_KEY }}

      - name: Set bot token
        run: echo "BOT_TOKEN=${{ steps.get-bot-token-main.outputs.token || steps.get-bot-token-version.outputs.token }}" >> $GITHUB_ENV

      - name: Set initial state
        if: github.event.action == 'requested'
        run: |
          echo "CI_STATE=pending" >> $GITHUB_ENV &&
          echo "CI_DESCRIPTION=In progress" >> $GITHUB_ENV

      - name: Set success state
        if: github.event.action == 'completed' && github.event.workflow_run.conclusion == 'success'
        run: |
          echo "CI_STATE=success" >> $GITHUB_ENV &&
          echo "CI_DESCRIPTION=Passed" >> $GITHUB_ENV

      - name: Set failure state
        if: github.event.action == 'completed' && github.event.workflow_run.conclusion == 'failure'
        run: |
          echo "CI_STATE=failure" >> $GITHUB_ENV &&
          echo "CI_DESCRIPTION=Failed" >> $GITHUB_ENV

      - name: Send status
        uses: octokit/request-action@dad4362715b7fb2ddedf9772c8670824af564f0d
        with:
          route: POST /repos/{owner}/{repo}/statuses/{sha}
          owner: ${{ github.event.repository.owner.login }}
          repo: ${{ github.event.repository.name }}
          sha: ${{ github.event.workflow_run.head_sha }}
          context: Status / CI
          state: ${{ env.CI_STATE }}
          description: ${{ env.CI_DESCRIPTION }}
          target_url: ${{ github.event.workflow_run.html_url }}
          GITHUB_TOKEN: ${{ env.SECRET_TOKEN || env.BOT_TOKEN }}
