name: CI

on:
  push:
    branches-ignore:
      - '__*'

concurrency: ci-${{ github.sha }}

jobs:
  install:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Install
        uses: cluerise/actions/install@main

  type-check:
    name: Check types
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Install
        uses: cluerise/actions/install@main
      - name: Check types
        run: pnpm run tc
        env:
          CI: true

  lint:
    name: Lint files
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Install
        uses: cluerise/actions/install@main

      - name: Lint files
        run: pnpm run lint all
        env:
          CI: true
