name: CI

on: push

concurrency: ci-${{ github.sha }}

jobs:
  install:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Install
        uses: cluerise/actions/install@main
        with:
          manager: pnpm

  lint:
    name: Lint files
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Install
        uses: cluerise/actions/install@main
        with:
          manager: pnpm

      - name: Lint files
        run: pnpm run lint all
        env:
          CI: true
