name: Lint PR title

on:
  pull_request:
    types: [opened, edited, synchronize]
  workflow_call:
    inputs:
      manager:
        type: string
        description: Package manager (pnpm, npm, or yarn)
      command:
        type: string
        description: Lint command to run
        default: pnpm run lint commit
      __external-call:
        type: boolean
        description: Do not use this input, it is an internal value to identify the workflow_call event
        default: true

jobs:
  lint-pr-title:
    name: Lint PR title
    runs-on: ubuntu-latest
    if: github.event.action != 'opened' || github.event.pull_request.user.login != 'dependabot[bot]'
    env:
      INPUT_MANAGER: ${{ inputs.manager }}
      INPUT_COMMAND: ${{ inputs.command || 'pnpm run lint commit' }}
      INPUT_EXTERNAL_CALL: ${{ inputs.__external-call || false }}

    steps:
      - name: Install (main)
        if: env.INPUT_EXTERNAL_CALL == 'false'
        uses: cluerise/actions/install@main

      - name: Install (version)
        if: env.INPUT_EXTERNAL_CALL == 'true'
        uses: cluerise/actions/install@v2.2.1
        with:
          manager: ${{ env.INPUT_MANAGER }}

      - name: Lint title
        run: echo -n "${{ github.event.pull_request.title }}" | ${{ env.INPUT_COMMAND }}
