name: Lint PR title

on:
  workflow_call:
    inputs:
      command:
        type: string
        description: Lint command to run
        default: 'npm run lint:commit'

jobs:
  lint-pr-title:
    name: Lint PR title
    runs-on: ubuntu-latest
    if: github.event.action != 'opened' || github.event.pull_request.user.login != 'dependabot[bot]'
    env:
      INPUT_COMMAND: ${{ inputs.command || 'npm run lint commit' }}

    steps:
      - name: Install
        uses: cluerise/actions/install@v2.1.1

      - name: Lint title
        run: echo -n "${{ github.event.pull_request.title }}" | ${{ env.INPUT_COMMAND }}
