name: Lint PR title

on:
  workflow_call:
    inputs:
      manager:
        type: string
        description: Package manager (pnpm, npm, or yarn)
      command:
        type: string
        description: Lint command to run
        default: pnpm run lint commit

jobs:
  lint-pr-title:
    name: Lint PR title
    runs-on: ubuntu-latest
    if: github.event.action != 'opened' || github.event.pull_request.user.login != 'dependabot[bot]'

    steps:
      - name: Install
        uses: cluerise/actions/install@v3.0.1
        with:
          manager: ${{ inputs.manager }}

      - name: Lint title
        run: echo -n "${{ github.event.pull_request.title }}" | ${{ inputs.command }}
