name: Lint PR title

on:
  workflow_call:
    inputs:
      manager:
        type: string
        description: Package manager (pnpm, npm, or yarn)
      command:
        type: string
        description: Lint command to run
      npm-config-userconfig:
        type: string
        description: NPM configuration file path
    secrets:
      npm-auth-token:
        description: NPM authentication token for private packages
        required: false
env:
  INPUT_MANAGER: ${{ inputs.manager }}
  INPUT_COMMAND: ${{ inputs.command || 'pnpm run lint commit' }}
  NPM_AUTH_TOKEN: ${{ secrets.npm-auth-token }}
  NPM_CONFIG_USERCONFIG: ${{ inputs.npm-config-userconfig }}

permissions:
  contents: read

jobs:
  lint-pr-title:
    name: Lint PR title
    runs-on: ubuntu-latest
    if: github.event.action != 'opened' || github.event.pull_request.user.login != 'dependabot[bot]'

    steps:
      - name: Install
        uses: cluerise/actions/install@v6.0.1
        with:
          manager: ${{ env.INPUT_MANAGER }}

      - name: Lint title
        run: echo -n '${{ github.event.pull_request.title }}' | ${{ env.INPUT_COMMAND }}
