name: Lint PR title

on:
  workflow_call:
    inputs:
      manager:
        type: string
        description: Package manager (pnpm, npm, or yarn)
      command:
        type: string
        description: Lint command to run

jobs:
  lint-pr-title:
    name: Lint PR title
    runs-on: ubuntu-latest
    if: github.event.action != 'opened' || github.event.pull_request.user.login != 'dependabot[bot]'
    env:
      INPUT_MANAGER: ${{ inputs.manager }}
      INPUT_COMMAND: ${{ inputs.command || 'pnpm run lint commit' }}

    steps:
      - name: Install
        uses: cluerise/actions/install@v4.2.8
        with:
          manager: ${{ env.INPUT_MANAGER }}

      - name: Lint title
        run: echo -n "${{ github.event.pull_request.title }}" | ${{ env.INPUT_COMMAND }}
