name: Rebase PR (main)

on:
  issue_comment:
    types: [created]

permissions:
  contents: write

jobs:
  rebase-pr:
    name: Rebase PR
    runs-on: ubuntu-latest
    if: |
      github.event.issue.pull_request != null &&
      github.event.comment.body == '/rebase'

    steps:
      - name: Get bot token
        id: get-bot-token
        uses: cluerise/actions/get-github-app-token@main
        with:
          app-id: ${{ vars.CLUERISE_PUBLIC_BOT_APP_ID }}
          app-private-key: ${{ secrets.CLUERISE_PUBLIC_BOT_APP_PRIVATE_KEY }}

      - name: Rebase PR
        uses: cluerise/actions/rebase-pr@main
        with:
          token: ${{ steps.get-bot-token.outputs.token }}
          squash: true
