name: Rebase PR

on:
  workflow_call:
    inputs:
      app-id:
        type: string
        description: GitHub app ID
      pr-id:
        type: string
        description: ID of the pull request to rebase
      squash:
        type: boolean
        description: Whether to squash the commits in the pull request
    secrets:
      token:
        description: GitHub access token
        required: false
      app-private-key:
        description: GitHub app private key
        required: false

permissions:
  contents: write

jobs:
  rebase-pr:
    name: Rebase PR
    runs-on: ubuntu-latest
    env:
      INPUT_APP_ID: ${{ inputs.app-id }}
      INPUT_PR_ID: ${{ inputs.pr-id }}
      INPUT_SQUASH: ${{ inputs.squash }}
      SECRET_TOKEN: ${{ secrets.token }}
      SECRET_APP_PRIVATE_KEY: ${{ secrets.app-private-key }}

    steps:
      - name: Check required secrets
        if: env.SECRET_TOKEN == '' && (env.INPUT_APP_ID == '' || env.SECRET_APP_PRIVATE_KEY == '')
        run: exit 1

      - name: Get bot token
        id: get-bot-token
        if: env.SECRET_TOKEN == ''
        uses: cluerise/actions/get-github-app-token@v6.0.4
        with:
          app-id: ${{ env.INPUT_APP_ID }}
          app-private-key: ${{ env.SECRET_APP_PRIVATE_KEY }}

      - name: Rebase PR
        uses: cluerise/actions/rebase-pr@v6.0.4
        with:
          token: ${{ env.SECRET_TOKEN || steps.get-bot-token.outputs.token }}
          pr-id: ${{ env.INPUT_PR_ID }}
          squash: ${{ env.INPUT_SQUASH }}
